definitions:
  notes.JustContent:
    properties:
      content:
        type: string
    type: object
  notes.Note:
    properties:
      content:
        type: string
      created_at:
        description: Managed by db with default value
        type: string
      id:
        type: integer
      updated_at:
        description: Managed by db with trigger
        type: string
    type: object
  users.User:
    properties:
      created_at:
        description: Managed by db with default value
        type: string
      updated_at:
        description: Managed by db with trigger
        type: string
      username:
        description: Primary key
        type: string
    type: object
  users.UserSerializer:
    properties:
      password:
        type: string
      username:
        type: string
    type: object
info:
  contact:
    name: Github
    url: https://github.com/theBigRoomXXL/notes/
  description: A simple REST API for a simple note taking app.
  license:
    name: MIT
    url: https://github.com/TheBigRoomXXL/Notes/raw/main/LICENCE.md
  title: Nøtes API
  version: 0.0.1
paths:
  /notes:
    get:
      consumes:
      - application/json
      - ' application/x-www-form-urlencoded'
      description: Perform a Full Text Search on your notes. Ordered by most recent
        update.
      parameters:
      - description: FTS query
        in: query
        name: search
        type: string
      produces:
      - application/json
      - ' text/html'
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/notes.Note'
            type: array
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/notes.Note'
      summary: List your notes
      tags:
      - notes
    post:
      consumes:
      - application/json
      - ' application/x-www-form-urlencoded'
      description: Save a note to the database and return the ID
      parameters:
      - description: The content of your note. Id is ignored
        in: body
        name: note
        required: true
        schema:
          $ref: '#/definitions/notes.JustContent'
      produces:
      - application/json
      - ' text/html'
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/notes.Note'
            type: array
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/notes.Note'
      summary: Create a notes
      tags:
      - notes
  /notes/{id}:
    delete:
      consumes:
      - application/json
      - ' application/x-www-form-urlencoded'
      description: Remove a record from the database
      parameters:
      - description: The note identifier
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      - ' text/html'
      responses:
        "204":
          description: ""
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/notes.Note'
      summary: Delete a notes
      tags:
      - notes
    put:
      consumes:
      - application/json
      - ' application/x-www-form-urlencoded'
      description: Default behavior is just to update the record in the DB and return
        200 but if the content of the note is empty then it's treated as a DELETE
        request and return 204.
      parameters:
      - description: The note identifier
        in: path
        name: id
        required: true
        type: integer
      - description: The content of your note.
        in: body
        name: note
        required: true
        schema:
          $ref: '#/definitions/notes.JustContent'
      produces:
      - application/json
      - ' text/html'
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/notes.Note'
            type: array
        "204":
          description: ""
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/notes.Note'
      summary: Update or delete a notes
      tags:
      - notes
  /users/login:
    post:
      consumes:
      - application/json
      - ' application/x-www-form-urlencoded'
      description: 'Try to login. "Accept: text/html" will trigger a redirect. "Accept:
        application/json" will send back the user object.'
      parameters:
      - description: username and password for authentification
        in: body
        name: userCredential
        required: true
        schema:
          $ref: '#/definitions/users.UserSerializer'
      produces:
      - application/json
      - ' text/html'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/users.User'
        "302":
          description: ""
        "401":
          description: login failed
          schema:
            type: string
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/users.User'
      summary: Login
      tags:
      - users
swagger: "2.0"
